import fs from "node:fs";
import path from "node:path";
import { Readable } from "node:stream";

/** Where uploaded files live. Implement this for S3/R2 later; callers only use these methods. */
export interface StorageProvider {
  readonly name: string;
  put(key: string, data: Uint8Array): Promise<void>;
  /** Streams the file, or a byte range of it (both ends inclusive). */
  open(key: string, range?: { start: number; end: number }): Promise<{ stream: ReadableStream<Uint8Array>; size: number } | null>;
  delete(key: string): Promise<void>;
}

class LocalStorage implements StorageProvider {
  readonly name = "local";
  private root() {
    return path.resolve(process.env.UPLOAD_DIR || path.join(process.cwd(), "uploads"));
  }

  /** Keys are generated by the server, but resolve defensively so a bad key can never leave the upload folder. */
  private resolve(key: string) {
    const root = this.root();
    const full = path.resolve(root, key);
    if (full !== root && !full.startsWith(root + path.sep)) throw new Error("Invalid storage key");
    return full;
  }

  async put(key: string, data: Uint8Array) {
    const full = this.resolve(key);
    await fs.promises.mkdir(path.dirname(full), { recursive: true });
    await fs.promises.writeFile(full, data);
  }

  async open(key: string, range?: { start: number; end: number }) {
    const full = this.resolve(key);
    let stat: fs.Stats;
    try {
      stat = await fs.promises.stat(full);
    } catch {
      return null;
    }
    const stream = fs.createReadStream(full, range ? { start: range.start, end: range.end } : undefined);
    return { stream: Readable.toWeb(stream) as unknown as ReadableStream<Uint8Array>, size: stat.size };
  }

  async delete(key: string) {
    await fs.promises.rm(this.resolve(key), { force: true });
  }
}

let provider: StorageProvider = new LocalStorage();
export function getStorage(): StorageProvider {
  return provider;
}
/** For tests, or to plug in another provider at startup. */
export function setStorage(next: StorageProvider) {
  provider = next;
}
